author:
  # 关键：确保你的头像文件放在 /images/ 文件夹下，并命名为 profile.png
  avatar           : "katong.png" 
  name             : "Shiming Fan"
  bio              : "Postgraduate Student in AI @ Sichuan University" # 简介
  location         : "Chengdu, China"
  employer         : "Shandong University of Business and Technology"
  email            : "2024410061@stu.scu.edu.cn" 

  # 学术链接（留空的不会显示）
  googlescholar    : "你的谷歌学术链接"
  github           : "Cola-Fsm" # 你的 GitHub ID
# 导航栏设置 (你可以去 _data/navigation.yml 进一步修改)
breadcrumbs              : false 
read_more                : "disabled"
talkmap_link             : false

# 统计分析（如果不需要追踪流量，保持 false）
analytics:
  provider               : "false"
main:
  - title: "About"
    url: /
  - title: "Publications"
    url: /publications/
  - title: "CV"
    url: /cv/
